name: "Check for metrics tests"
on:
  pull_request:
    types: [ opened, synchronize, labeled ]
    # Runs on PRs to main and all release branches
    branches:
      - main

jobs:
  metrics_test_check:
    if: "!contains(github.event.pull_request.labels.*.name, 'pr/no-metrics-test')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "checkout repo"
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
      - name: "Check for metrics modifications"
        run: ./.github/scripts/metrics_checker.sh
        shell: bash
